#!/usr/bin/env python3
"""Generates ui/AsciiArt.js, the empty-state illustrations.

Each picture is a lit shape sampled onto a 26 x 13 cell grid (two cells wide
per cell tall, so a circle stays round in a mono font) and mapped onto a
density ramp, the way classic ASCII art shades. Hand-drawn glyph grids were
tried first and read as scattered characters; shading is what makes a
picture at this size. Run from the repository root:

    python3 tools/ascii-art.py
"""
import math
from pathlib import Path

RAMP = " .\u00b7:;+=*#%@"
COLS, ROWS = 26, 13


def shade(v):
    v = max(0.0, min(1.0, v))
    return RAMP[min(len(RAMP) - 1, int(v * (len(RAMP) - 1) + 0.5))]


def render(f):
    return ["".join(shade(f((i + 0.5) / COLS * 2 - 1, (j + 0.5) / ROWS * 2 - 1)) for i in range(COLS)) for j in range(ROWS)]


def coin(x, y, r=0.86, lx=-0.5, ly=-0.6):
    """A sphere lit from the upper left, the stock ASCII-art subject."""
    d = math.hypot(x, y)
    if d > r:
        return 0.0
    z = math.sqrt(max(0.0, r * r - d * d)) / r
    return 0.18 + 0.82 * max(0.0, x / r * lx + y / r * ly + z * 0.75)


def clock(x, y):
    d = math.hypot(x, y)
    if 0.72 < d < 0.86:
        return 1.0
    if abs(x) < 0.07 and -0.55 < y < 0.05 or abs(y) < 0.09 and 0 < x < 0.42 or d < 0.09:
        return 1.0
    return 0.12 if d <= 0.72 else 0.0


def search(x, y):
    cx, cy = -0.22, -0.2
    hx, hy = x - cx, y - cy
    d = math.hypot(hx, hy)
    if 0.48 < d < 0.62:
        return 1.0
    if d <= 0.48:
        return 0.12 + 0.25 * max(0.0, -hx - hy)
    t = (hx + hy) / 2
    return 1.0 if 0.62 < t < 1.15 and abs(hx - hy) < 0.16 else 0.0


def filter_(x, y):
    top, mid = -0.8, 0.15
    if top <= y <= mid:
        w = 0.9 * (1 - (y - top) / (mid - top)) + 0.08
        if abs(x) <= w:
            return 0.35 + 0.33 * (1 - abs(x) / w) + 0.1 * (1 - (y - top) / (mid - top))
    return 0.8 if mid < y <= 0.85 and abs(x) < 0.1 else 0.0


def emboss(rows, glyph, col, row):
    line = list(rows[row])
    line[col - 1:col + 2] = [" ", glyph, " "]
    rows[row] = "".join(line)
    return rows


art = {
    "coin": emboss(render(coin), "\u20bf", 13, 6),
    "clock": render(clock),
    "search": render(search),
    "filter": render(filter_),
}

out = ["// Generated by tools/ascii-art.py; edit the shapes there, not here.", ".pragma library", "", "var art = {"]
for name, rows in art.items():
    out.append("    %s: [" % name)
    out.extend("        %s," % repr(r).replace("'", '"') for r in rows)
    out.append("    ],")
out += ["}", ""]
Path("ui/AsciiArt.js").write_text("\n".join(out), encoding="utf-8")
